name: mods_v2
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - ta-lib
  - jupyterlab
  - notebook
  - black
  - flake8
  - mypy
  - isort
  - pre-commit
  - pip
  - setuptools
  - wheel
  - pip:
      - -e .   # install mods_v2 in editable mode from pyproject.toml
